nextjs-repros-2:
  component: "@sls-next/serverless-component@1.17.0-alpha.7"
  inputs:
    runtime: "nodejs12.x"
    bucketName: nextjs-repros-2
    bucketRegion: us-west-1
    memory: 1024
    name:
      defaultLambda: nextjs-repros-default-lambda-2
      apiLambda: nextjs-repros-api-lambda-2
