# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:node13.6.0-chrome80-ff72
    environment:
      PORT: 3000

    resource_class: small
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile --ignore-engines
      - save_cache:
          paths:
            - ~/.cache/yarn
            - .next/cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build NextJS app
          command: |
            yarn run build
      - run:
          name: Run NextJS server
          background: true
          command: |
            yarn run start
      - run:
          name: Run Cypress tests
          command: yarn run cypress
      - store_artifacts:
          path: cypress/videos

workflows:
  version: 2
  build-deploy:
    jobs:
      - build